name: Renovate
on: push
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run renovate
        run: docker run --rm renovate/renovate --token ${{ secrets.GH_TOKEN }} ${{ github.repository }}
