name: Renovate
on: push
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run renovate
        run: docker run --rm -e "RENOVATE_TOKEN=${{ secrets.GITHUB_TOKEN }}" renovate/renovate
