name: Renovate
on: push
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run renovate
        uses: renovatebot/github-action@v32.0.1
        env:
          RENOVATE_TOKEN: ${{ secrets.GH_TOKEN }}
