name: Renovate
on: push
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm renovate/renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
